### PR TITLE
Sentinel 2 nbar index script

### PR DESCRIPTION
**Pull request by alexgleith**
Probably should be documented. And possibly should go in a different repo?

### CODE REVIEW

**Comment by woodcockr** [comment]
We are doing something similar to this but from the Argo Workflow configuration so we can spawn parallel jobs (for each date, to an overall limit). We do a similar thing for the LS archives x_ key (or in fact any arbitrary key to split on).

We are currently thinking the better option might be to split the yaml finding and indexing into two parts - whilst still preserving the streaming aspect for yaml finding so we they aren't all in memory at the same time. At the same time improve the ability to glob the keys. Something like:
1. s3 find the yamls with a solid bit of regex globbing so you can subset (assuming the key is useful enough to allow that to happen)
2. Group the yamls into batches and feed to queue
3. Second workflow monitors queue and grabs a batch spawning an indexing job in parallel, limited by the workflow tools (argo in our case).
Rinse and repeat.

Bottleneck would be writes to the database. Not sure how fast your processing goes and what db instance you are running but mines annoying me at the moment but I've only just started getting used to Aurora postgresql. Keen to hear other experiences.

**Comment by alexgleith** [comment]
I think implementing more dynamic globbing in `s3-find` would be great.

Handling parallelisation could be good too. But doing this work sequentially was _ok_.

Database bottlenecks have been alleviated for our implementation through the use of Aurora, which dynamically scales...

**Comment by woodcockr** [comment]
> Handling parallelisation could be good too. But doing this work sequentially was _ok_.
> 

I see two different kinds of parallelisation:
1. Workflow level (airflow, Argo, ...)  - batching up indexing/transformation tasks to workers
2. Worker level - workers using multi threading 

The ability to stream the yamls out rather than tar them is great but its made this into (multithreaded) single worker action. I’m thinking it might be useful to split the labour out a bit and in particular the dB connections, something like this- 
1. Workers Group A finds yamls using wizzy regex and batches them up, send to batch to queue for pickup by Worker Group B
2. Worker Group B uses a Read Only connection to database (which will scale on Aurora) and checks if the data is already indexed. Batches up any that haven’t and sends these to Worker Group C
3. Worker Group C uses the R/W connection to database and performs indexing. This group will need to recheck if data has been indexed before adding in case some other action added before it got to execute.

Not sure if this will make a great deal of difference as I haven’t checked where the performance bottleneck is in practice (aside watching the Aurora master instance peg its CPU usage). For an empty database bulk index its no different but for any updates across the whole database it should help balance the load across readers. The workflow tools (Airflow, Argo) can be used to split out workers and scale if we have the separate actions available.

> Database bottlenecks have been alleviated for our implementation through the use of Aurora, which dynamically scales...

My performance comment was related to _writes_ to the database and Aurora Postgres doesn’t dynamically scale for writes to my knowledge. I might try a bigger instance type and see how much difference it makes.

**Comment by alexgleith** [comment]
Hmm... to be honest I don't know much about Aurora and dynamic scaling, but I was running three fairly heaving indexing processes at the same time and the DB scaled up it's IOPS.

And yeah, the Airflow parallelisation is nice, so long as you can partition data by day/week/month/sensible partitioning unit.

**Comment by woodcockr** [comment]
> Hmm... to be honest I don't know much about Aurora and dynamic scaling, but I was running three fairly heaving indexing processes at the same time and the DB scaled up it's IOPS.

I was running 20 ;-)

When you say "scaled up it's IOPs". Do you mean it simply handled 1, then 2 then 3 well, or did it actually change configuration somehow (more cores, more memory, more instances)?

I suspect the former but would like to be certain.

**Comment by alexgleith** [comment]
>When you say "scaled up it's IOPs".

I really only mean the IOPs went up, instead of hitting a ceiling. haha, sounds like you've got more experience than I ;-)

**Comment by woodcockr** [comment]
> > When you say "scaled up it's IOPs".
> 
> I really only mean the IOPs went up, instead of hitting a ceiling. haha, sounds like you've got more experience than I ;-)

That's just cause I am really old now ;-)

**Comment by alexgleith** [comment]
>really old now

Yes, wi

**Pull request merged**
